Revert "add: function to disable buy/sell buttons"
This reverts commit a72fd2f524d75c52bd08f08e3518698c18f1196e.

error: buy/sell offer buttons not working fine